### ISSUE TITLE
添加账号的时候报错，以下是请求日志

### ISSUE THREAD

**Issue by Jesn** [Yanyutin753/fakeApiTool-One-API#10]
```
2023-11-21 06:56:21.810  INFO 1 --- [nio-8008-exec-6] c.y.f.interceptor.LoginCheckInterceptor  : 请求的url: http://10.1.0.5:8008/api/addToken
2023-11-21 06:56:21.816  INFO 1 --- [nio-8008-exec-6] c.y.f.interceptor.LoginCheckInterceptor  : Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwiZXhwIjoxNzAwNTkyNjA0fQ.b7ldpfB0XXXXXXXXXXXXXXXXXXX
2023-11-21 06:56:21.833  INFO 1 --- [nio-8008-exec-6] c.y.f.interceptor.LoginCheckInterceptor  : 令牌合法, 放行
2023-11-21 06:56:21.951  INFO 1 --- [nio-8008-exec-6] c.y.f.service.impl.apiServiceImpl        : HttpResponseProxy{HTTP/1.1 429 Too Many Requests [Date: Tue, 21 Nov 2023 06:56:21 GMT, Content-Type: application/json, Content-Length: 29, Connection: keep-alive, Report-To: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=DbrrobtDvK4joGluj42lMI9KzIfh3JH9f51%2BXwVC5kXnhj9%2FzVwXTyKTMiyMsDclRhmpzX3QXK1UNI7uyKVZME7iJQRONPKnfBjSj5b3J%2BPhi8Zx2yD2jJYyZVC0kLc4XXXXXXXXX"}],"group":"cf-nel","max_age":604800}, NEL: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}, Vary: Accept-Encoding, Strict-Transport-Security: max-age=15552000; includeSubDomains; preload, X-Content-Type-Options: nosniff, Server: cloudflare, CF-RAY: 829708491d1f9e64-SJC, alt-svc: h3=":443"; ma=86400] ResponseEntityProxy{[Content-Type: application/json,Content-Length: 29,Chunked: false]}}
2023-11-21 06:56:21.953  INFO 1 --- [nio-8008-exec-6] c.y.f.service.impl.apiServiceImpl        : {"detail":"service overload"}
org.json.JSONException: No value for access_token
	at org.json.JSONObject.get(JSONObject.java:355)
	at org.json.JSONObject.getString(JSONObject.java:515)
	at com.yyandywt99.fakeapitool.service.impl.apiServiceImpl.updateToken(apiServiceImpl.java:695)
	at com.yyandywt99.fakeapitool.service.impl.apiServiceImpl.addToken(apiServiceImpl.java:357)
	at com.yyandywt99.fakeapitool.controller.apiColltroller.addToken(apiColltroller.java:59)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1072)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:965)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:555)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:623)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:209)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:91)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:481)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:390)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:926)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1790)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:829)
	
```

**Comment by Yanyutin753** [comment]
添加账号不行 fakeopen关了

**Comment by Yanyutin753** [comment]
直接添加token吧，后面pandora作者会出一个新的服务

**Comment by Jesn** [comment]
> 直接添加token吧，后面pandora作者会出一个新的服务

添加token，貌似也要输入账号密码的

**Comment by Yanyutin753** [comment]
可以随便填，添加账号密码是为了之后在拿token，你要是觉得不方便就随便填，或者先填上去

**Comment by Jesn** [comment]
> 可以随便填，添加账号密码是为了之后在拿token，你要是觉得不方便就随便填，或者先填上去

嗯，已经添加成功了
